name: Publish NuGet package

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'Publish version'
        required: true
        type: string
        default: 1.0.8
      release:
        description: 'publish release'
        type: boolean
        default: true

jobs:
  build_and_test:
    name: Build and test
    uses: ./.github/workflows/test.yml
  publish:
    needs: build_and_test
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Prepare version string
        id: version
        env:
          TAG: ${{ github.ref_name }}
        run: echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Download runtimes
        uses: actions/download-artifact@v4
        with:
          name: runtimes
          path: runtimes
      - name: Restore project
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release -p:Version="${{ inputs.version }}" --no-restore
      - name: Test
        run: dotnet test -c Release -p:Version="${{ inputs.version }}" --no-restore --no-build --verbosity normal
      - name: Pack
        run: dotnet pack -c Release -p:Version="${{ inputs.version }}" -o . --no-restore --no-build
      - name: Publish
        run: dotnet nuget push "Onigwrap.${{ inputs.version }}.nupkg" -k "${{ secrets.NUGET_API_KEY }}" -s https://nuget.loongnix.cn/v3/index.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Onigwrap.${{ inputs.version }}
          path: Onigwrap.${{ inputs.version }}.nupkg
